### ISSUE TITLE
Assertion error: assert( len(data) == 2 )

### ISSUE THREAD

**Issue by Gim6626** [claremacrae/markdown_to_dokuwiki.py#9]
Could not use `markdown_to_dokuwiki.py`, got following error:
```
$ python2 markdown_to_dokuwiki.py input.md 
Traceback (most recent call last):
  File "markdown_to_dokuwiki.py", line 156, in <module>
    return_code = main( files )
  File "markdown_to_dokuwiki.py", line 145, in main
    return_code =+ convert_file( filename )
  File "markdown_to_dokuwiki.py", line 138, in convert_file
    process_pandoc_jason( data )
  File "markdown_to_dokuwiki.py", line 110, in process_pandoc_jason
    assert( len(data) == 2 )
AssertionError
```

Tested on simple `input.md` file generated from Doxygen:
```
# Source files list #

1. **`libfooplatform.c`**

    Implementation of the library's initialization/deinitialization.

1. **`libfooplatform.h`**

    Description of the Foo API public part.
```

**Comment by claremacrae** [comment]
Thanks for reporting this. What version of Python are you using please?

**Comment by Gim6626** [comment]
```
$ python2 -V
Python 2.7.14
```
